select * from Tasks

select * from import_table;

CREATE TABLE ImportedTasks (
    TASKID NUMBER,
    TASKNAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(1000),
    DEADLINE DATE,
    ASSIGNEDTOUSERID NUMBER,
    STATUSID NUMBER,
    CATEGORYID NUMBER,
    PRIORITYID NUMBER,
    PROJECTID NUMBER,
    PARENTTASKID NUMBER
);

LOAD DATA
INFILE 'C:\external\data.json'
APPEND INTO TABLE ImportedTasks
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
 TASKID      "TRIM(:TASKID)",
 TASKNAME    "UPPER(TRIM(:TASKNAME))",
 DESCRIPTION "UPPER(TRIM(:DESCRIPTION))",
 DEADLINE    DATE 'DD.MM.YYYY',
 ASSIGNEDTOUSERID "TRIM(:ASSIGNEDTOUSERID)",
 STATUSID    "TRIM(:STATUSID)",
 CATEGORYID  "TRIM(:CATEGORYID)",
 PRIORITYID  "TRIM(:PRIORITYID)",
 PROJECTID   "TRIM(:PROJECTID)",
 PARENTTASKID "TRIM(:PARENTTASKID)"
)
